newProject("C:/Users/niels/DIANA_code/trial_3D", 1000, {} )
setModelAnalysisAspects( [ "STRUCT" ] )
setModelDimension( "3D" )
setGeneralizedPlaneStrainType( "OPLSHR" )
setDefaultMeshOrder( "LINEAR" )
setDefaultMesherType( "HEXQUAD" )
